version: '2.1'
services:
  ethereumhost:
    build: ./server/
    ports:
      - 30303:30303
    stdin_open: true
  ethereumclient:
    build: ./client/
    ports:
      - 30304:30303
      - 8545:8545
    links:
      - "ethereumhost:host"
  app:
    build: ./dapp-wallet
    command: meteor --allow-superuser
    working_dir: /home/app
    ports:
      - 3000:3000
    volumes:
      - ./dapp-wallet/app/:/home/app

