version: '2.1'
services:
  ethereumhost:
    build: ./server/
    ports:
      - 30303:30303
  ethereumclient:
    build: ./client/
    links:
      - "ethereumhost:host"
    ports:
      - 30304:30303
    command: "geth bootnode --genkey=boot.key"